# PyTorch Embeddings
Author: Pierre Nugues

Principal component analysis on characters of Salammbô. French and English chapters

In [2]:
import numpy as np
import torch
import torch.nn as nn

In [6]:
embedding = nn.Embedding(10, 3)
embedding.weight

Parameter containing:
tensor([[ 1.1959, -0.3126, -0.5955],
        [-2.2378, -0.2234, -0.6788],
        [-0.6869, -0.9685, -0.6124],
        [-0.2697,  0.6882, -2.6541],
        [ 0.2830,  0.1994, -1.9261],
        [ 0.9152, -1.9225,  0.6298],
        [-0.0843, -0.6159, -0.4984],
        [ 0.2563,  0.7507,  0.0735],
        [ 0.1870,  0.7367,  1.0119],
        [ 0.5591,  1.0836, -0.3769]], requires_grad=True)

In [7]:
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding(input)

tensor([[[-2.2378, -0.2234, -0.6788],
         [-0.6869, -0.9685, -0.6124],
         [ 0.2830,  0.1994, -1.9261],
         [ 0.9152, -1.9225,  0.6298]],

        [[ 0.2830,  0.1994, -1.9261],
         [-0.2697,  0.6882, -2.6541],
         [-0.6869, -0.9685, -0.6124],
         [ 0.5591,  1.0836, -0.3769]]], grad_fn=<EmbeddingBackward0>)

In [8]:
embedding = nn.Embedding(10, 3, padding_idx=0)
embedding.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.5867,  1.0278, -1.1050],
        [ 0.7670,  0.4030,  2.4984],
        [ 0.0433,  0.1374,  0.4019],
        [ 0.4572,  1.1916, -1.4292],
        [ 0.7983,  1.5811, -0.8106],
        [-0.2262, -0.2157, -0.3240],
        [-2.0494,  1.3482,  1.2141],
        [ 1.0569,  0.5791,  0.1668],
        [-0.1369, -1.9696, -0.0646]], requires_grad=True)

In [9]:
input = torch.LongTensor([[0, 2, 0, 5]])
embedding(input)

tensor([[[ 0.0000,  0.0000,  0.0000],
         [ 0.7670,  0.4030,  2.4984],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.7983,  1.5811, -0.8106]]], grad_fn=<EmbeddingBackward0>)

In [14]:
embedding_p = nn.Embedding(10, 3, padding_idx=0)
embedding_p.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 1.1206,  0.8750, -0.0967],
        [-0.5118, -0.0965,  0.0698],
        [-2.0774,  1.1132,  0.6116],
        [ 1.5907, -1.2987,  0.3181],
        [ 0.6128, -1.6291, -0.2988],
        [-0.9502, -1.9463, -1.4547],
        [-0.6794, -0.1608,  1.1222],
        [ 1.1581, -1.1795, -1.3160],
        [ 0.6329, -0.8094, -1.0147]], requires_grad=True)

In [15]:
embeddings = nn.Embedding.from_pretrained(
  torch.FloatTensor(embedding_p.weight), 
  freeze=False, 
  padding_idx=0)

In [16]:
embeddings.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 1.1206,  0.8750, -0.0967],
        [-0.5118, -0.0965,  0.0698],
        [-2.0774,  1.1132,  0.6116],
        [ 1.5907, -1.2987,  0.3181],
        [ 0.6128, -1.6291, -0.2988],
        [-0.9502, -1.9463, -1.4547],
        [-0.6794, -0.1608,  1.1222],
        [ 1.1581, -1.1795, -1.3160],
        [ 0.6329, -0.8094, -1.0147]], requires_grad=True)